# https://oai.github.io/Documentation/specification-content.html
swagger: 2.0
openapi: 3.1.0
info:
  title: 8koi food api for CRUD operations
  version: 1.1.1
servers:
  - url: https://food-api-henry.onrender.com
paths:
  #* --------------------------- GET /diets/all ---------------------------- *#
  /diets/all:
    get:
      summary: Get all diet types
      responses:
        "200":
          description: all went OK
          content:
            application/json:
              schema:
                type: array
                items:
                $ref: "#/components/schemas/diet"
        "400":
          description: SERVER ERROR
  #* -------------------------- GET /diets/id ----------------------------- *#
  /diets/id/{id}:
    parameters:
      - $ref: id
        in: path
        required: true
    get:
      summary: Get a single diet by UUID
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/diet"
        "400":
          description: SERVER ERROR
  #* -------------------------- GET /diets/related ----------------------------- *#
  /diets/related:
    parameters:
      - $ref: dietName
        in: query
        required: true
    get:
      summary: Gets all recipes related to that diet (DB & API)
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: array
                items:
                $ref: "#/components/schemas/diet"
        "400":
          description: SERVER ERROR
  #* --------------------------- POST: /diets/add  ---------------------------- *#
  /diets/add:
    parameters:
      - $ref: dietName
        in: query
        required: true
    post:
      summary: Add a diet by name to DB
      responses:
        "201":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/diet"
        "400":
          description: SERVER ERROR
  #* --------------------------- DELETE: /diets/del  ---------------------------- *#
  /diets/del:
    parameters:
      - $ref: dietId
        in: query
        required: true
    delete:
      summary: Add a diet by name to DB
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/diet"
        "400":
          description: SERVER ERROR
