export default [
  {
    name: "Cannellini Bean and Asparagus Salad with Mushrooms",
    desc: 'Cannellini Bean and Asparagus Salad with Mushrooms requires approximately <b>45 minutes</b> from start to finish. This main course has <b>482 calories</b>, <b>31g of protein</b>, and <b>6g of fat</b> per serving. This gluten free, dairy free, lacto ovo vegetarian, and vegan recipe serves 6 and costs <b>$1.35 per serving</b>. 309 people were impressed by this recipe. Head to the store and pick up grain mustard, sea salt, lemon zest, and a few other things to make it today. It is brought to you by foodandspice.blogspot.com. Taking all factors into account, this recipe <b>earns a spoonacular score of 70%</b>, which is pretty good. Similar recipes are <a href="https://spoonacular.com/recipes/cannellini-bean-salad-422994">Cannellini Bean Salad</a>, <a href="https://spoonacular.com/recipes/refreshing-cannellini-bean-salad-113127">Refreshing Cannellini Bean Salad</a>, and <a href="https://spoonacular.com/recipes/cannellini-and-green-bean-salad-33177">Cannellini-and-Green Bean Salad</a>.',
    healthyness: 100,
    imageUrl: "https://spoonacular.com/recipeImages/782585-312x231.jpg",
    steps: [
      "Rinse the cannellini beans and soak for 8 hours or overnight in several inches of water.",
      "Drain and rinse, then transfer to a medium saucepan and cover with fresh water.",
      "Add the curry leaves or bay leaf and bring to a boil. Reduce heat to medium-low, cover, and simmer for 1 hour or until the beans are tender but not falling apart.",
      "Drain and transfer to a large salad bowl.Meanwhile, snap the woody ends off of the asparagus spears and steam the spears for 6 minutes or until just tender but still retaining their crunch.",
      "Transfer to the salad bowl.Now cook the mushrooms.",
      "Heat the oil in a large skillet over high heat. As soon as the oil is hot, drop in the mushrooms and cook, stirring constantly, for 5 minutes or until the mushrooms begin to brown and lose some of their liquid.",
      "Transfer to the bowl with the asparagus.To make the dressing, combine the tarragon, lemon zest, garlic, lemon juice, olive oil and mustard in a small food processor or blender. Process until smooth.",
      "Pour the dressing over the salad, season with salt and pepper, and toss.",
      "Serve at room temperature or chilled.",
    ],
    ingredientsList: [],
    diets: ["gluten free", "dairy free", "lacto ovo vegetarian", "vegan"],
    createdInDb: false,
  },
  {
    name: "Cauliflower, Brown Rice, and Vegetable Fried Rice",
    desc: 'You can never have too many Chinese recipes, so give Cauliflower, Brown Rice, and Vegetable Fried Rice a try. This recipe serves 8 and costs $1.12 per serving. This hor d\'oeuvre has <b>192 calories</b>, <b>7g of protein</b>, and <b>6g of fat</b> per serving. Head to the store and pick up broccoli, sesame seeds, soy sauce, and a few other things to make it today. 3689 people were impressed by this recipe. It is brought to you by fullbellysisters.blogspot.com. It is a good option if you\'re following a <b>gluten free, dairy free, lacto ovo vegetarian, and vegan</b> diet. From preparation to the plate, this recipe takes roughly <b>30 minutes</b>. Overall, this recipe earns a <b>spectacular spoonacular score of 100%</b>. If you like this recipe, you might also like recipes such as <a href="https://spoonacular.com/recipes/cauliflower-brown-rice-and-vegetable-fried-rice-1584601">Cauliflower, Brown Rice, and Vegetable Fried Rice</a>, <a href="https://spoonacular.com/recipes/cauliflower-brown-rice-and-vegetable-fried-rice-1238897">Cauliflower, Brown Rice, and Vegetable Fried Rice</a>, and <a href="https://spoonacular.com/recipes/cauliflower-brown-rice-and-vegetable-fried-rice-1230097">Cauliflower, Brown Rice, and Vegetable Fried Rice</a>.',
    healthyness: 75,
    imageUrl: "https://spoonacular.com/recipeImages/716426-312x231.jpg",
    steps: [
      'Remove the cauliflower\'s tough stem and reserve for another use. Using a food processor, pulse cauliflower florets until they resemble rice or couscous. You should end up with around four cups of "cauliflower rice."',
      "Heat 1T butter and 1T oil in a large skillet over medium heat.",
      "Add garlic and the white and light green pieces of scallion. Sauté about a minute.",
      "Add the cauliflower to the pan. Stir to coat with oil, then spread out in pan and let sit; you want it cook a bit and to caramelize (get a bit brown), which will bring out the sweetness. After a couple of minutes, stir and spread out again.",
      "Add cold rice (it separates easily, so it won't clump up during cooking), plus the additional grapeseed and coconut oil or butter. Raise heat to medium-high. Toss everything together and, again, spread the mixture out over the whole pan and press a bit into the bottom.",
      "Let it sit for about two minutes—so the rice can get toasted and a little crispy.",
      "Add the peas and broccoli and stir again.",
      "Drizzle soy sauce and toasted sesame oil over rice.Cook for another minute or so and turn off heat.",
      "Add chopped scallion tops and toss.I like to toast some sesame seeds in a dry pan; I sprinkle these and some more raw, chopped scallion over the top of the rice for added flavor and crunch.Season to taste with salt and, if you'd like, more soy sauce. Keep in mind that if you're serving this with something salty and saucy (ie. teriyaki chicken) you may want to hold off on adding too much salt to the fried rice.",
    ],
    ingredientsList: [],
    diets: ["gluten free", "dairy free", "lacto ovo vegetarian", "vegan"],
    createdInDb: false,
  },
  {
    name: "Berry Banana Breakfast Smoothie",
    desc: 'If you want to add more <b>lacto ovo vegetarian</b> recipes to your recipe box, Berry Banana Breakfast Smoothie might be a recipe you should try. One portion of this dish contains about <b>21g of protein</b>, <b>10g of fat</b>, and a total of <b>457 calories</b>. This recipe serves 1 and costs $2.07 per serving. 689 people have tried and liked this recipe. It works well as a rather inexpensive breakfast. A mixture of banana, graham cracker crumbs, vanilla yogurt, and a handful of other ingredients are all it takes to make this recipe so yummy. From preparation to the plate, this recipe takes roughly <b>5 minutes</b>. It is brought to you by Pink When. Overall, this recipe earns a <b>super spoonacular score of 99%</b>. Similar recipes include <a href="https://spoonacular.com/recipes/berry-banana-breakfast-smoothie-1364145">Berry Banana Breakfast Smoothie</a>, <a href="https://spoonacular.com/recipes/berry-banana-breakfast-smoothie-1405583">Berry Banana Breakfast Smoothie</a>, and <a href="https://spoonacular.com/recipes/berry-banana-breakfast-smoothie-1601311">Berry Banana Breakfast Smoothie</a>.',
    healthyness: 64,
    imageUrl: "https://spoonacular.com/recipeImages/715497-312x231.jpg",
    steps: [
      "Take some yogurt in your favorite flavor and add 1 container to your blender.",
      "Add in the berries, banana, and soy milk and blend. Top your glass with a few graham cracker crumbs and serve.",
    ],
    ingredientsList: [],
    diets: ["lacto ovo vegetarian"],
    createdInDb: false,
  },
  {
    name: "Red Lentil Soup with Chicken and Turnips",
    desc: 'Red Lentil Soup with Chicken and Turnips might be a good recipe to expand your main course repertoire. This recipe serves 8 and costs $3.0 per serving. One serving contains <b>477 calories</b>, <b>27g of protein</b>, and <b>20g of fat</b>. It is brought to you by Pink When. 1866 people have tried and liked this recipe. It can be enjoyed any time, but it is especially good for <b>Autumn</b>. From preparation to the plate, this recipe takes approximately <b>55 minutes</b>. It is a good option if you\'re following a <b>gluten free and dairy free</b> diet. Head to the store and pick up salt and pepper, canned tomatoes, flat leaf parsley, and a few other things to make it today. Overall, this recipe earns a <b>spectacular spoonacular score of 99%</b>. If you like this recipe, you might also like recipes such as <a href="https://spoonacular.com/recipes/red-lentil-and-chicken-soup-682185">Red Lentil and Chicken Soup</a>, <a href="https://spoonacular.com/recipes/red-lentil-and-chicken-soup-1058971">Red Lentil and Chicken Soup</a>, and <a href="https://spoonacular.com/recipes/red-lentil-soup-34121">Red-Lentil Soup</a>.',
    healthyness: 100,
    imageUrl: "https://spoonacular.com/recipeImages/715415-312x231.jpg",
    steps: [
      "To a large dutch oven or soup pot, heat the olive oil over medium heat.",
      "Add the onion, carrots and celery and cook for 8-10 minutes or until tender, stirring occasionally.",
      "Add the garlic and cook for an additional 2 minutes, or until fragrant. Season conservatively with a pinch of salt and black pepper.To the pot, add the tomatoes, turnip and red lentils. Stir to combine. Stir in the vegetable stock and increase the heat on the stove to high. Bring the soup to a boil and then reduce to a simmer. Simmer for 20 minutes or until the turnips are tender and the lentils are cooked through.",
      "Add the chicken breast and parsley. Cook for an additional 5 minutes. Adjust seasoning to taste.",
      "Serve the soup immediately garnished with fresh parsley and any additional toppings. Enjoy!",
    ],
    ingredientsList: [],
    diets: ["gluten free", "dairy free"],
    createdInDb: false,
  },
  {
    name: "Asparagus and Pea Soup: Real Convenience Food",
    desc: 'Asparagus and Pea Soup: Real Convenience Food requires approximately <b>20 minutes</b> from start to finish. Watching your figure? This gluten free, dairy free, paleolithic, and lacto ovo vegetarian recipe has <b>217 calories</b>, <b>11g of protein</b>, and <b>8g of fat</b> per serving. This recipe serves 2. For <b>$1.78 per serving</b>, this recipe <b>covers 25%</b> of your daily requirements of vitamins and minerals. <b>Autumn</b> will be even more special with this recipe. It works well as a hor d\'oeuvre. 207 people have tried and liked this recipe. It is brought to you by fullbellysisters.blogspot.com. A mixture of vegetable broth, evoo, garlic, and a handful of other ingredients are all it takes to make this recipe so yummy. All things considered, we decided this recipe <b>deserves a spoonacular score of 96%</b>. This score is outstanding. Try <a href="https://spoonacular.com/recipes/asparagus-and-pea-soup-real-convenience-food-1393979">Asparagus and Pea Soup: Real Convenience Food</a>, <a href="https://spoonacular.com/recipes/asparagus-and-pea-soup-real-convenience-food-1376201">Asparagus and Pea Soup: Real Convenience Food</a>, and <a href="https://spoonacular.com/recipes/asparagus-and-pea-soup-real-convenience-food-1362341">Asparagus and Pea Soup: Real Convenience Food</a> for similar recipes.',
    healthyness: 100,
    imageUrl: "https://spoonacular.com/recipeImages/716406-312x231.jpg",
    steps: [
      "Chop the garlic and onions.",
      "Saute the onions in the EVOO, adding the garlic after a couple of minutes; cook until the onions are translucent.",
      "Add the whole bag of asparagus and cover everything with the broth. Season with salt and pepper and a pinch of red pepper flakes, if using.Simmer until the asparagus is bright green and tender (if you've thawed the asparagus it will only take a couple of minutes). Turn off the heat and puree using an immersion blender.",
      "Add peas (the heat of the soup will quickly thaw them) and puree until smooth; add more until it reaches the thickness you like.Top with chives and a small dollop of creme fraiche or sour cream or greek yogurt.",
    ],
    ingredientsList: [],
    diets: [
      "gluten free",
      "dairy free",
      "paleolithic",
      "lacto ovo vegetarian",
      "primal",
      "vegan",
    ],
    createdInDb: false,
  },
  {
    name: "Garlicky Kale",
    desc: 'Garlicky Kale requires approximately <b>45 minutes</b> from start to finish. This side dish has <b>170 calories</b>, <b>2g of protein</b>, and <b>15g of fat</b> per serving. This recipe serves 2. For <b>69 cents per serving</b>, this recipe <b>covers 17%</b> of your daily requirements of vitamins and minerals. 19 people have made this recipe and would make it again. This recipe from Foodista requires balsamic vinegar, garlic, curly kale, and olive oil. It is a good option if you\'re following a <b>gluten free, dairy free, paleolithic, and lacto ovo vegetarian</b> diet. With a spoonacular <b>score of 99%</b>, this dish is outstanding. Try <a href="https://spoonacular.com/recipes/garlicky-kale-248759">Garlicky Kale</a>, <a href="https://spoonacular.com/recipes/garlicky-kale-1267347">Garlicky Kale</a>, and <a href="https://spoonacular.com/recipes/garlicky-kale-1584523">Garlicky Kale</a> for similar recipes.',
    healthyness: 83,
    imageUrl: "https://spoonacular.com/recipeImages/644387-312x231.jpg",
    steps: [
      "Heat the olive oil in a large pot over medium heat.",
      "Add the kale and cover.Stir occasionally until the volume of the kale is reduced by half. Uncover.",
      "Add garlic and basalmic.Allow to cook for about another 30 seconds or so, mixing well so that the garlic and vinegar are well distributed.",
      "Serve hot.",
    ],
    ingredientsList: [],
    diets: [
      "gluten free",
      "dairy free",
      "paleolithic",
      "lacto ovo vegetarian",
      "primal",
      "whole 30",
      "vegan",
    ],
    createdInDb: false,
  },
  {
    name: "Red Kidney Bean Jambalaya",
    desc: 'Red Kidney Bean Jambalayan is a main course that serves 6. One portion of this dish contains approximately <b>18g of protein</b>, <b>6g of fat</b>, and a total of <b>393 calories</b>. For <b>$1.68 per serving</b>, this recipe <b>covers 33%</b> of your daily requirements of vitamins and minerals. 53 people were glad they tried this recipe. A mixture of vegetable stock, tomatoes, onion, and a handful of other ingredients are all it takes to make this recipe so flavorful. It is a good option if you\'re following a <b>gluten free, dairy free, lacto ovo vegetarian, and vegan</b> diet. This recipe is typical of Cajun cuisine. It is brought to you by foodandspice.blogspot.com. From preparation to the plate, this recipe takes roughly <b>45 minutes</b>. Overall, this recipe earns a <b>tremendous spoonacular score of 99%</b>. Users who liked this recipe also liked <a href="https://spoonacular.com/recipes/red-kidney-bean-jambalaya-1407231">Red Kidney Bean Jambalaya</a>, <a href="https://spoonacular.com/recipes/red-kidney-bean-salad-94525">Red Kidney Bean Salad</a>, and <a href="https://spoonacular.com/recipes/red-kidney-bean-curry-80686">Red Kidney Bean Curry</a>.',
    healthyness: 96,
    imageUrl: "https://spoonacular.com/recipeImages/782601-312x231.jpg",
    steps: [
      "Rinse the kidney beans and brown rice separately. Cover the kidney beans with water and soak for 8 hours or overnight. In a separate bowl, cover the brown rice with water and soak for 8 hours or overnight.",
      "Drain and rinse the kidney beans, then transfer to a medium saucepan and cover with fresh water. Bring to a boil, reduce heat to medium-low, cover, and simmer for 1 hour or until just tender but not falling apart.",
      "Drain and set aside.",
      "Heat the oil in a large saucepan over medium heat. When hot, add the onion and saut for 5 minutes. Now add the garlic, carrots, celery and green beans, and stir for another 5 minutes. Next add the tomatoes, red pepper, eggplant, sage, thyme, marjoram and celery seed, and continue to stir for another few minutes.",
      "Pour in the vegetable stock, liquid smoke, rice and the cooked kidney beans. Bring to a boil, reduce heat to medium low, cover, and cook, stirring occasionally, for 45 minutes or until the rice is tender.",
      "Add water as necessary if the stew becomes too dry.Season with sriracha, salt and pepper, and taste for seasoning  add more liquid smoke, sriracha, salt, pepper or herbs as desired.",
    ],
    ingredientsList: [],
    diets: ["gluten free", "dairy free", "lacto ovo vegetarian", "vegan"],
    createdInDb: false,
  },
  {
    name: "Chicken Fajita Stuffed Bell Pepper",
    desc: 'Chicken Fajita Stuffed Bell Pepper takes approximately <b>45 minutes</b> from beginning to end. Watching your figure? This gluten free recipe has <b>526 calories</b>, <b>50g of protein</b>, and <b>24g of fat</b> per serving. For <b>$4.35 per serving</b>, you get a main course that serves 3. 159 people have made this recipe and would make it again. This recipe is typical of Mexican cuisine. This recipe from Pink When requires cumin, cilantro, salsa, and chili powder. All things considered, we decided this recipe <b>deserves a spoonacular score of 98%</b>. This score is amazing. Users who liked this recipe also liked <a href="https://spoonacular.com/recipes/stuffed-bell-peppers-551310">Stuffed Bell Peppers</a>, <a href="https://spoonacular.com/recipes/stuffed-bell-pepper-1348405">Stuffed Bell Pepper</a>, and <a href="https://spoonacular.com/recipes/stuffed-bell-pepper-526845">Stuffed Bell Pepper</a>.',
    healthyness: 85,
    imageUrl: "https://spoonacular.com/recipeImages/795751-312x231.jpg",
    steps: [
      "To get started heat oven to 35",
      "Mix salt, pepper, cilantro, cumin, chili powder, and quinoa together and place to the side.",
      "Cut the bell pepper in half (if you havent already) and clean out the seeds.",
      "Layer quinoa and then grilled chicken into the pepper, and then top each with cheese.",
      "Place in the oven for about 10 minutes until the bell pepper has softened.Chicken Fajita Stuffed Bell Pepper",
      "Top with avocado and serve with shredded lettuce and salsa for a complete meal.This is SO GOOD! I love bell peppers, and I love all of these flavors that are married together that make this chicken fajita stuffed bell pepper so amazing. I could seriously just eat the flavored quinoa all by itself.If you are looking for even more delicious and healthy recipes, make sure you head over to the Simple Fit Forty tab under the cooking section of this blog. We have all of our favorite healthy recipes listed for you right there in one spot. You can also drool over out latest on the Simple Fit Forty Instagram page.If you are looking to get healthy and fit, come and join the super secret and awesome Simple Fit Forty Lifestyle community over on Facebook. We would love to have you join!",
    ],
    ingredientsList: [],
    diets: ["gluten free"],
    createdInDb: false,
  },
  {
    name: "Hummus and Za'atar",
    desc: 'You can never have too many middl eastern recipes, so give Hummus and Za\'atar a try. This recipe serves 4. One portion of this dish contains about <b>34g of protein</b>, <b>31g of fat</b>, and a total of <b>778 calories</b>. For <b>$1.61 per serving</b>, this recipe <b>covers 44%</b> of your daily requirements of vitamins and minerals. If you have chickpeas, olive oil, sea salt, and a few other ingredients on hand, you can make it. It works best as a marinade, and is done in about <b>45 minutes</b>. It is a good option if you\'re following a <b>gluten free, dairy free, lacto ovo vegetarian, and vegan</b> diet. 35 people have made this recipe and would make it again. It is brought to you by foodandspice.blogspot.com. Overall, this recipe earns a <b>great spoonacular score of 98%</b>. <a href="https://spoonacular.com/recipes/chopped-hummus-dip-with-zaatar-180958">Chopped Hummus Dip with Za\'atar</a>, <a href="https://spoonacular.com/recipes/mediterranean-hummus-toast-with-zaatar-1067472">Mediterranean Hummus Toast with Za’atar</a>, and <a href="https://spoonacular.com/recipes/hummus-deviled-eggs-with-zaatar-exercise-challenge-1195539">Hummus Deviled Eggs with Za’atar {Exercise Challenge}</a> are very similar to this recipe.',
    healthyness: 100,
    imageUrl: "https://spoonacular.com/recipeImages/766453-312x231.jpg",
    steps: [
      "Rinse the chickpeas and soak for 8 hours or overnight in several inches of water.",
      "Drain and rinse, then transfer to a medium saucepan and cover with fresh water. Bring to a boil, reduce heat to medium-low, cover, and simmer for 1 to 1 1/2 hours or until soft.",
      "Drain, reserving the cooking liquid. (If using canned chickpeas, rinse thoroughly.)Meanwhile, toast the pine nuts in a dry unoiled skillet or saucepan over medium-low heat, tossing or stirring frequently, for 10 minutes or until lightly browned.",
      "Transfer the chickpeas to a food processor and add the pine nuts, 2 tablespoons of olive oil, 1/4 cup of the reserved chickpea cooking liquid (or water if using canned chicpeas), the tahini, garlic, lemon juice and salt. Process until smooth, adding more of the reserved chickpea cooking liquid or water as necessary to reach a light creamy consistency. Taste for seasoning and add more salt or lemon juice as desired.",
      "Transfer the hummus to a shallow bowl and drizzle with olive oil.",
      "Sprinkle with za'atar and paprika, and serve with chopped fresh vegetables or toasted pita triangles.Refrigerate leftover hummus for a few days or freeze for up to a month.",
    ],
    ingredientsList: [],
    diets: ["gluten free", "dairy free", "lacto ovo vegetarian", "vegan"],
    createdInDb: false,
  },
  {
    name: "Easy Homemade Rice and Beans",
    desc: 'Easy Homemade Rice and Beans is a main course that serves 2. One serving contains <b>446 calories</b>, <b>19g of protein</b>, and <b>4g of fat</b>. For <b>$1.06 per serving</b>, this recipe <b>covers 26%</b> of your daily requirements of vitamins and minerals. A mixture of optional: of hot sauce, canned tomatoes, water, and a handful of other ingredients are all it takes to make this recipe so yummy. This recipe from cooking2perfection.blogspot.com has 471 fans. It is a good option if you\'re following a <b>gluten free, dairy free, lacto ovo vegetarian, and vegan</b> diet. From preparation to the plate, this recipe takes around <b>35 minutes</b>. Overall, this recipe earns a <b>tremendous spoonacular score of 98%</b>. <a href="https://spoonacular.com/recipes/easy-homemade-rice-and-beans-1311839">Easy Homemade Rice and Beans</a>, <a href="https://spoonacular.com/recipes/easy-homemade-rice-and-beans-1303021">Easy Homemade Rice and Beans</a>, and <a href="https://spoonacular.com/recipes/easy-homemade-rice-and-beans-1230117">Easy Homemade Rice and Beans</a> are very similar to this recipe.',
    healthyness: 60,
    imageUrl: "https://spoonacular.com/recipeImages/716627-312x231.jpg",
    steps: [
      "Heat the olive oil in a large pot over medium heat.",
      "Add onions and saute until soft, or for about 5 minutes.",
      "Add all other remaining ingredients and stir together. Increase the heat to medium high and bring to a boil. Cover and reduce heat to medium low so that the mixture simmers. Cook for 15-20 minutes, or until rice is fluffy and liquid is absorbed.*",
      "Serve with salsa, cheese, and sour cream.",
    ],
    ingredientsList: [],
    diets: ["gluten free", "dairy free", "lacto ovo vegetarian", "vegan"],
    createdInDb: false,
  },
  {
    name: "Tuscan White Bean Soup with Olive Oil and Rosemary",
    desc: 'Tuscan White Bean Soup with Olive Oil and Rosemary is a <b>gluten free, dairy free, lacto ovo vegetarian, and vegan</b> recipe with 6 servings. This main course has <b>242 calories</b>, <b>16g of protein</b>, and <b>1g of fat</b> per serving. For <b>50 cents per serving</b>, this recipe <b>covers 19%</b> of your daily requirements of vitamins and minerals. It will be a hit at your <b>Autumn</b> event. 22 people found this recipe to be tasty and satisfying. Head to the store and pick up olive oil, rosemary, garlic, and a few other things to make it today. It is brought to you by Foodista. From preparation to the plate, this recipe takes roughly <b>45 minutes</b>. With a spoonacular <b>score of 79%</b>, this dish is good. If you like this recipe, take a look at these similar recipes: <a href="https://spoonacular.com/recipes/white-bean-soup-with-pasta-and-rosemary-oil-drizzle-855454">White Bean Soup with Pastan and Rosemary Oil Drizzle</a>, <a href="https://spoonacular.com/recipes/tuscan-white-bean-and-fennel-stew-with-orange-and-rosemary-105383">Tuscan White Bean and Fennel Stew With Orange and Rosemary</a>, and <a href="https://spoonacular.com/recipes/tuscan-white-bean-soup-1054940">Tuscan White Bean Soup</a>.',
    healthyness: 94,
    imageUrl: "https://spoonacular.com/recipeImages/664147-312x231.jpg",
    steps: [
      "Rinse the beans thoroughly and place them in a 7-quart slow cooker along with the water, onion, garlic, and bay leaf. Cover and cook on LOW for about 8 hours, or until the beans are nice and tender.",
      "Remove the bay leaf. Using a handheld immersion blender, puree the remaining ingredients to the desired texture.",
      "Add the salt to taste.Ladle the soup into bowls.",
      "Drizzle with the olive oil, sprinkle with rosemary, and serve.",
    ],
    ingredientsList: [],
    diets: ["gluten free", "dairy free", "lacto ovo vegetarian", "vegan"],
    createdInDb: false,
  },
  {
    ingredientsList: [
      {
        name: "some inedient",
        amount: 6,
        unit: "grams",
      },
    ],
    id: "c1c8f55c-31a3-4f52-8312-0ca04ed39d93",
    name: "Most tasty food ever",
    desc: "kekwkokokokokoko",
    healthyness: 16,
    steps: ["111s1111111", "222222222", "333333333"],
    imageUrl: "htpp:yomaaaofat.com",
    createdInDb: true,
  },
  {
    ingredientsList: [
      {
        name: "some ingredient",
        amount: 69,
        unit: "grams",
      },
    ],
    id: "0ae734c6-460c-4db0-a52e-a8aa4dcb52fe",
    name: "lame af name",
    desc: "kekwkokokokokkoko",
    healthyness: 14,
    steps: ["111111s1111111", "222222222222", "3333333dd33"],
    imageUrl: "htpp:yomaaamasofat.com",
    createdInDb: true,
  },
];
